p8105_hw2_rc3520.Rmd
================
Ruyi Chen
2023-10-03

``` r
library (tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(tidyr)
library(readxl)
library(readr)
```

# Probelm 1

## Clean the data in pols-month.csv.

### Use separate() to break up the variable mon into integer variables year, month, and day; replace month number with month name; create a president variable taking values gop and dem, and remove prez_dem and prez_gop; and remove the day variable.

``` r
 pols_month_df= 
  read_csv("./data/pols-month.csv") %>%
  janitor::clean_names() %>%
  separate(col = mon,into = c("year","month","day"),sep = '-', convert = TRUE) %>%
  mutate(
    year = as.integer(year), 
    month = as.integer(month), 
    month = month.abb[month],
    day = as.integer(day),
    president = ifelse(prez_gop, "dem", "gop")
    ) %>%
  select(-prez_dem, -prez_gop, -day)
pols_month_df
```

## Clean the data in snp.csv using a similar process to the above. For consistency across datasets, arrange according to year and month, and organize so that year and month are the leading columns.

``` r
snp_df=
    read_csv("./data/snp.csv") %>%
    drop_na() %>%
    janitor::clean_names() %>%
    separate(date, into  = c("month", "day", "year")) %>%
  mutate(year = as.integer(year), 
         year=ifelse(year<23, year+2000, year+1900),
         month = as.integer(month), 
         month = month.abb[month],
         day = as.integer(day)) %>%
  select(year,month,close,-day) %>%
  arrange(year,month) 
snp_df
```

\##Third, tidy the unemployment data so that it can be merged with the
previous datasets. This process will involve switching from “wide” to
“long” format; ensuring that key variables have the same name; and
ensuring that key variables take the same values.

``` r
unemployment_df=
    read_csv("./data/unemployment.csv",
             col_names = TRUE,
              show_col_types = FALSE) %>%
    janitor::clean_names() %>%
  drop_na() %>%
  pivot_longer(jan:dec, names_to = "month", values_to = "unemployment_percent") %>%
  mutate(month = str_to_title(month)) %>%
  arrange(year, month)
unemployment_df
```

\##Join the datasets by merging snp into pols, and merging unemployment
into the result

``` r
pols_snp_df = left_join(pols_month_df, snp_df, by = c("year", "month"))
pols_snp_unemployment_df = left_join(pols_snp_df, unemployment_df, by = c("year", "month"))

pols_snp_unemployment_df
```

\##Write a short paragraph about these datasets. Explain briefly what
each dataset contained, and describe the resulting dataset (e.g. give
the dimension, range of years, and names of key variables).
pols_month_df dataset includes 822 observations and 9 variables (key
variables include year, month and president) containing information
about the national politicians These data describe whether the policians
are democratic or republican between 1947 and 2015. It also contains the
number of national politicians(governors/senators/representatives) in
U.S. I create a new variable president in order to combine pre_gop and
prez_dem. snp_df includes 787 observations and 3 variables including
year, month and close. They describe the closing values of S&P stock
index from between 1950 and 2015. unemployment_df includes 804
observations and 3 variables including year, month and
unemployment_rate. It shows the unemployment rate in each month between
1948 and 2014. pols_snp_unemployment_df shows the number of republic /
democratic presidents and number of governors/ senators/ representatives
from 1947 to 2015. It also shows the closing values of the S&P stock
index between 1950 and 2015 and unemployment rate between Jan/1948 to
Jun/2014.

\#Problem 2 \##clean the Mr. Trash Wheel sheet

``` r
mr_trash_wheel = read_excel("./data/202309 Trash Wheel Collection Data.xlsx",
                     sheet = "Mr. Trash Wheel",
                     range=cell_cols("A:N")) %>%
  janitor::clean_names() %>%
  drop_na() %>%
  mutate(
    sports_balls = as.integer(round(sports_balls)), 
    year = as.integer(year), 
    dumpster = as.numeric(dumpster), 
    homes_powered = (weight_tons * (500/30)),
    catg = "mr trash wheel") %>%
    # Create a variable catg to help with the combination of the datasets
  select(catg, everything())
mr_trash_wheel
```

    ## # A tibble: 584 × 15
    ##    catg  dumpster month  year date                weight_tons volume_cubic_yards
    ##    <chr>    <dbl> <chr> <int> <dttm>                    <dbl>              <dbl>
    ##  1 mr t…        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ##  2 mr t…        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ##  3 mr t…        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ##  4 mr t…        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ##  5 mr t…        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ##  6 mr t…        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ##  7 mr t…        7 May    2014 2014-05-21 00:00:00        1.91                  8
    ##  8 mr t…        8 May    2014 2014-05-28 00:00:00        3.7                  16
    ##  9 mr t…        9 June   2014 2014-06-05 00:00:00        2.52                 14
    ## 10 mr t…       10 June   2014 2014-06-11 00:00:00        3.76                 18
    ## # ℹ 574 more rows
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>

\##import, clean, and organize the data for Professor Trash Wheel

``` r
professor_trash_wheel = read_excel("./data/202309 Trash Wheel Collection Data.xlsx",
                                   sheet = "Professor Trash Wheel")%>%
                        janitor::clean_names() %>%
                        drop_na(dumpster) %>%
                        mutate(homes_powered = (weight_tons * (500/30)),
                          year=as.integer(year),
                          catg = "prof trash wheel") %>%
  # Create a variable catg to help with the combination of the datasets
  select(catg, everything())
professor_trash_wheel
```

    ## # A tibble: 106 × 14
    ##    catg  dumpster month  year date                weight_tons volume_cubic_yards
    ##    <chr>    <dbl> <chr> <int> <dttm>                    <dbl>              <dbl>
    ##  1 prof…        1 Janu…  2017 2017-01-02 00:00:00        1.79                 15
    ##  2 prof…        2 Janu…  2017 2017-01-30 00:00:00        1.58                 15
    ##  3 prof…        3 Febr…  2017 2017-02-26 00:00:00        2.32                 18
    ##  4 prof…        4 Febr…  2017 2017-02-26 00:00:00        3.72                 15
    ##  5 prof…        5 Febr…  2017 2017-02-28 00:00:00        1.45                 15
    ##  6 prof…        6 March  2017 2017-03-30 00:00:00        1.71                 15
    ##  7 prof…        7 April  2017 2017-04-01 00:00:00        1.82                 15
    ##  8 prof…        8 April  2017 2017-04-20 00:00:00        2.37                 15
    ##  9 prof…        9 May    2017 2017-05-10 00:00:00        2.64                 15
    ## 10 prof…       10 May    2017 2017-05-26 00:00:00        2.78                 15
    ## # ℹ 96 more rows
    ## # ℹ 7 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, homes_powered <dbl>

## calculate total weight of trash collected by Professor Trash Wheel

``` r
professor_trash_wheel %>%
  select(weight_tons) %>%
  colSums()
```

    ## weight_tons 
    ##      216.26

\##import, clean, and organize the data for Gwynnda

``` r
gwynnda = read_excel("./data/202309 Trash Wheel Collection Data.xlsx",
                                   sheet = "Gwynnda Trash Wheel")%>%
                        janitor::clean_names() %>%
                        drop_na(dumpster) %>%
                        mutate(homes_powered = (weight_tons * (500/30)),
                          cigarette_butts = as.integer(cigarette_butts),
                          year=as.integer(year),
                          catg = "gwynnda trash wheel") %>%
    # Create a variable catg to help with the combination of the datasets
  select(catg, everything())
gwynnda
```

    ## # A tibble: 155 × 13
    ##    catg  dumpster month  year date                weight_tons volume_cubic_yards
    ##    <chr>    <dbl> <chr> <int> <dttm>                    <dbl>              <dbl>
    ##  1 gwyn…        1 July   2021 2021-07-03 00:00:00        0.93                 15
    ##  2 gwyn…        2 July   2021 2021-07-07 00:00:00        2.26                 15
    ##  3 gwyn…        3 July   2021 2021-07-07 00:00:00        1.62                 15
    ##  4 gwyn…        4 July   2021 2021-07-16 00:00:00        1.76                 15
    ##  5 gwyn…        5 July   2021 2021-07-30 00:00:00        1.53                 15
    ##  6 gwyn…        6 Augu…  2021 2021-08-11 00:00:00        2.06                 15
    ##  7 gwyn…        7 Augu…  2021 2021-08-14 00:00:00        1.9                  15
    ##  8 gwyn…        8 Augu…  2021 2021-08-16 00:00:00        2.16                 15
    ##  9 gwyn…        9 Augu…  2021 2021-08-16 00:00:00        2.6                  15
    ## 10 gwyn…       10 Augu…  2021 2021-08-17 00:00:00        3.21                 15
    ## # ℹ 145 more rows
    ## # ℹ 6 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <int>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   homes_powered <dbl>

\##Calculate The total number of cigarette butts collected by Gwynnda in
July of 2021

``` r
gwynnda %>%
  filter(year == "2021",month == "July")%>%
  select(cigarette_butts)%>%
  colSums()
```

    ## cigarette_butts 
    ##           16300

\##Combine these there data to produce a single tidy dataset

``` r
mr_prof_trash_wheel = left_join(mr_trash_wheel, professor_trash_wheel, by = c("dumpster"))
mr_prof_gwynnda_trash_wheel= left_join(mr_prof_trash_wheel,gwynnda , by = c("dumpster"))
mr_prof_gwynnda_trash_wheel
```

    ## # A tibble: 585 × 40
    ##    catg.x         dumpster month.x year.x date.x              weight_tons.x
    ##    <chr>             <dbl> <chr>    <int> <dttm>                      <dbl>
    ##  1 mr trash wheel        1 May       2014 2014-05-16 00:00:00          4.31
    ##  2 mr trash wheel        2 May       2014 2014-05-16 00:00:00          2.74
    ##  3 mr trash wheel        3 May       2014 2014-05-16 00:00:00          3.45
    ##  4 mr trash wheel        4 May       2014 2014-05-17 00:00:00          3.1 
    ##  5 mr trash wheel        5 May       2014 2014-05-17 00:00:00          4.06
    ##  6 mr trash wheel        6 May       2014 2014-05-20 00:00:00          2.71
    ##  7 mr trash wheel        7 May       2014 2014-05-21 00:00:00          1.91
    ##  8 mr trash wheel        8 May       2014 2014-05-28 00:00:00          3.7 
    ##  9 mr trash wheel        9 June      2014 2014-06-05 00:00:00          2.52
    ## 10 mr trash wheel       10 June      2014 2014-06-11 00:00:00          3.76
    ## # ℹ 575 more rows
    ## # ℹ 34 more variables: volume_cubic_yards.x <dbl>, plastic_bottles.x <dbl>,
    ## #   polystyrene.x <dbl>, cigarette_butts.x <dbl>, glass_bottles.x <dbl>,
    ## #   plastic_bags.x <dbl>, wrappers.x <dbl>, sports_balls <int>,
    ## #   homes_powered.x <dbl>, catg.y <chr>, month.y <chr>, year.y <int>,
    ## #   date.y <dttm>, weight_tons.y <dbl>, volume_cubic_yards.y <dbl>,
    ## #   plastic_bottles.y <dbl>, polystyrene.y <dbl>, cigarette_butts.y <dbl>, …

\##Description about the datasets mr_trash_wheel includes 584
observations and 15variables.Key variables include year, month, dumpster
and weight. professor_trash_wheel includes 106 observations and 14
variables. Key variables include year, month, dumpster and weight. The
total weight of trash collected by Professor Trash Wheel is 216.26 tons.
gwynnda includes 155 observations and 13 variables. Key variables
include year, month, dumpster, weight, and cigarette butts. The total
number of cigarette butts collected by Gwynnda in July of 2021 is
1.63^{4}

# Problem 3

\##Import, clean, and tidy the dataset of mci_baseline

``` r
mci_baseline =
  read_csv("./data/MCI_baseline.csv", skip = 1) %>% 
  janitor::clean_names() %>%
  mutate(
    sex = case_match(sex, 1 ~ "Male",0 ~ "Female"),
    apoe4 = case_match(apoe4, 1 ~ "Carrier", 0 ~ "Non_carrier")) 
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Age at onset
    ## dbl (5): ID, Current Age, Sex, Education, apoe4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
mci_baseline_df = filter(mci_baseline, age_at_onset == "." | age_at_onset > current_age)
mci_baseline_df
```

    ## # A tibble: 479 × 6
    ##       id current_age sex    education apoe4       age_at_onset
    ##    <dbl>       <dbl> <chr>      <dbl> <chr>       <chr>       
    ##  1     1        63.1 Female        16 Carrier     .           
    ##  2     2        65.6 Female        20 Carrier     .           
    ##  3     3        62.5 Male          16 Carrier     66.8        
    ##  4     4        69.8 Female        16 Non_carrier .           
    ##  5     5        66   Male          16 Non_carrier 68.7        
    ##  6     6        62.5 Male          16 Non_carrier .           
    ##  7     7        66.5 Male          18 Non_carrier 74          
    ##  8     8        67.2 Female        18 Non_carrier .           
    ##  9     9        66.7 Female        16 Non_carrier .           
    ## 10    10        64.1 Female        18 Non_carrier .           
    ## # ℹ 469 more rows

\##Discussion on the dataframe mci_baseline After importing the data, I
tidy the variable names by using ‘janitor::clean_names’ and deleting the
first line(description on the variables) by using ‘skip’.Then, I make
sure that sex and APOE4 carrier status are appropriately encoded by
using ‘mutate’ so that 1 and 0 will be “Male” and “Female” under sex and
will be “Carrier” and “Non_carrier” under apoes. And I also use ‘filter’
and generate the dataframe ‘mci_baseline_df’ to represent the data that
meets the stated inclusion criteria, either missing `age_at_onset` value
or `age_at_onset` is larger than `current_age` at baseline. \### 483
numbers of patients were recruited. \### \`Of these 479 developed MCI.
\### Average baseline age is 65.5419355. \### 29.8578199 % of women in
the study are APOE4 carriers.

\##Import, clean, and tidy the dataset of mci_amyloid

``` r
mci_amyloid =
  read_csv("./data/mci_amyloid.csv", skip = 1) %>% 
  janitor::clean_names() %>%
  rename(id = study_id)
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (5): Baseline, Time 2, Time 4, Time 6, Time 8
    ## dbl (1): Study ID
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
mci_amyloid
```

    ## # A tibble: 487 × 6
    ##       id baseline    time_2      time_4      time_6      time_8     
    ##    <dbl> <chr>       <chr>       <chr>       <chr>       <chr>      
    ##  1     1 0.1105487   <NA>        0.109325197 0.104756131 0.107257697
    ##  2     2 0.107481183 0.109157373 0.109457839 0.105729713 0.10661845 
    ##  3     3 0.106087034 0.108744509 0.106065035 <NA>        0.106152357
    ##  4     4 0.109251358 0.108699686 0.110540386 0.107476797 0.111212209
    ##  5     5 0.107950408 0.112273883 0.115139677 0.106606054 0.106052066
    ##  6     6 0.112426974 0.112853415 0.11143945  0.110279277 0.114982747
    ##  7     7 0.112246391 <NA>        0.104251905 0.112485583 0.112055612
    ##  8     8 0.109563372 0.109470828 <NA>        0.108742168 0.110268552
    ##  9     9 0.112101884 0.109781199 0.108832888 <NA>        <NA>       
    ## 10    10 0.1116094   0.111592149 <NA>        <NA>        0.110051296
    ## # ℹ 477 more rows

\##Description: After importing the data with read_csv, I tidy the
variable names by using janitor::clean_names and deleting the first
line(description on the variables) by using skip. I also use rename to
change the column name “study_id” to “id” so that it can be further
match to the column name in mci_baseline.There are 487 people enrolled
in this study. There are 6 vairables including id and biomarker
measurement recorded at baseline,time_2, time_4, time_6 and time_8.

\##Combine the demographic and biomarker datasets

``` r
mci_baseline_amyloid = 
  inner_join(mci_baseline_df, mci_amyloid) 
```

    ## Joining with `by = join_by(id)`

``` r
#export the result as a CSV to your data directory.
write_csv(mci_baseline_amyloid, "./data/baseline_amyloid.csv")
```

\##Description: By applying inner join, I keep participants who exist on
both demographic and biomarker datasets. There are 471 numbers of
participants who appear on both datasets. Since there are 8 more
participants in biomarker datasets than participants in demographic
datasets, some participants appear in only the baseline or amyloid
datasets. Among these 471 participants, 142 are carriers which
43.6619718 % of them are females and 56.3380282 % of them are males; 471
participants, 329 are non_carriers which 43.4650456 % of them are
females and 56.5349544 % of them are males.
